# ndarray

## 创建 ndarray
| 函数   | 案例   |  说明
| ---- | ---- | ---- |
|   array   |   np.array([6, 7.5, 8])   |   根据列表、元组、数组等序列类型创建ndarray   |
|   asarray   |   np.asarray([6, 7.5, 8])   |   将输入转换为ndarray，如果输入本身是ndarray，则不会复制   |
|   arange   |   np.arange(2, 8, 3)   |   根据指定的 start、stop、step 创建 ndarray   |
|   zeros   |   np.zeros(3， 7)   |   创建数值全为0的 ndarray   |
|   ones   |   np.ones(10)   |   创建数值全为1的 ndarray   |
|   empty   |   np.empty((2, 3, 2))   |   创建 ndarray，分配内存空间但不赋值   |


### 1. np.array

In [4]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]

print("创建一维ndarray")
arr1 = np.array(data1)
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)


创建一维ndarray
[6.  7.5 8.  0.  1. ]
1
(5,)
float64
[6.  7.5 8.  0.  1. ]


In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

print("创建二维数组")
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int64


### 2. np.asarray / np.arange

In [9]:
print(np.asarray(data1))
print(np.arange(start= 2, stop= 8, step= 3))

[6.  7.5 8.  0.  1. ]
[2 5]


### 3. 常量 ndarray

In [3]:
print(np.zeros(10))
print(np.ones((3, 5)))
print(np.empty((2, 3, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[-0.00000000e+000 -0.00000000e+000]
  [-5.43472210e-323  0.00000000e+000]
  [ 2.12199579e-314  0.00000000e+000]]

 [[ 0.00000000e+000  0.00000000e+000]
  [ 1.77229088e-310  3.50977866e+064]
  [ 0.00000000e+000  0.00000000e+000]]]


## dtype
- 一个特殊的对象
- 由类名+元素位长表示，如：float64、s10
- 可以方便地读写磁盘二进制数据流
- 类名包括int、float、complex、bool、object(python对象)、_string(固定长度字符串)、unicode

## ndarray的运算

- 不需要编写循环就能执行数组与数组、数组与标量之间的运算
- 也称为矢量化计算

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

print("\n数组与数组计算")
print(arr * arr)

print("\n数组与标量计算")
print(1 / arr)

[[1 2 3]
 [4 5 6]]

数组与数组计算
[[ 1  4  9]
 [16 25 36]]

数组与标量计算
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


## 索引和切片
