# ndarray

## 创建 ndarray
| 函数   | 案例   |  说明
| ---- | ---- | ---- |
|   array   |   np.array([6, 7.5, 8])   |   根据列表、元组、数组等序列类型创建ndarray   |
|   asarray   |   np.asarray([6, 7.5, 8])   |   将输入转换为ndarray，如果输入本身是ndarray，则不会复制   |
|   arange   |   np.arange(2, 8, 3)   |   根据指定的 start、stop、step 创建 ndarray   |
|   zeros   |   np.zeros(3， 7)   |   创建数值全为0的 ndarray   |
|   ones   |   np.ones(10)   |   创建数值全为1的 ndarray   |
|   empty   |   np.empty((2, 3, 2))   |   创建 ndarray，分配内存空间但不赋值   |


### 1. np.array

In [4]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]

print("创建一维ndarray")
arr1 = np.array(data1)
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)


创建一维ndarray
[6.  7.5 8.  0.  1. ]
1
(5,)
float64
[6.  7.5 8.  0.  1. ]


In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

print("创建二维数组")
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int64


### 2. np.asarray / np.arange

In [9]:
print(np.asarray(data1))
print(np.arange(start= 2, stop= 8, step= 3))

[6.  7.5 8.  0.  1. ]
[2 5]


### 3. 常量 ndarray

In [3]:
print(np.zeros(10))
print(np.ones((3, 5)))
print(np.empty((2, 3, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[-0.00000000e+000 -0.00000000e+000]
  [-5.43472210e-323  0.00000000e+000]
  [ 2.12199579e-314  0.00000000e+000]]

 [[ 0.00000000e+000  0.00000000e+000]
  [ 1.77229088e-310  3.50977866e+064]
  [ 0.00000000e+000  0.00000000e+000]]]


## dtype
- 一个特殊的对象
- 由类名+元素位长表示，如：float64、s10
- 可以方便地读写磁盘二进制数据流
- 类名包括int、float、complex、bool、object(python对象)、_string(固定长度字符串)、unicode

## ndarray的运算

- 不需要编写循环就能执行数组与数组、数组与标量之间的运算
- 也称为矢量化计算

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

print("\n数组与数组计算")
print(arr * arr)

print("\n数组与标量计算")
print(1 / arr)

[[1 2 3]
 [4 5 6]]

数组与数组计算
[[ 1  4  9]
 [16 25 36]]

数组与标量计算
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


## 索引和切片


### 一维数组切片
ndarray 与 Python list 都可以进行切片，区别是：
- 将标量赋值给 ndarray 切片，会自动广播到切片到每个元素中
- ndarray 的切片是原始数组的视图，而不是复制为新的数组，在视图上修改会同步到原始 ndarray
- 这样目的是节约内存空间，ndarray 通常都比较大
- 如果需要复制为新的数组，使用 arr.copy()

In [8]:
import numpy as np

arr = np.arange(10)
print(arr)

arr_copy1 = arr[5:8]
arr_copy1[:] = 12
print(arr)

arr_copy2 = arr[1:3].copy()
arr_copy2[:] = 15

print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12  8  9]
[ 0  1  2  3  4 12 12 12  8  9]


### 多维数组切片

In [16]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("原始数组为：")
print(arr2d)

# 同维度上切片
print("\n在axis1上切片：")
print(arr2d[:2])

print("\n在axis1、axis2上切片：")
print(arr2d[:2, 1:])

# 低维度切片
print("\n选择特定的索引，得到低维度切片：")
print(arr2d[1, :2])
print(arr2d[:2, 1])

原始数组为：
[[1 2 3]
 [4 5 6]
 [7 8 9]]

在axis1上切片：
[[1 2 3]
 [4 5 6]]

在axis1、axis2上切片：
[[2 3]
 [5 6]]

选择特定的索引，得到低维度切片：
[4 5]
[2 5]
[0.         1.         1.41421356 1.73205081 2.         3.46410162
 3.46410162 3.46410162 2.82842712 3.        ]


## 元素级别函数
这类函数比较多，有一元函数、二元函数

In [18]:
import numpy as np

arr1 = np.arange(5)
arr2 = np.array([6, 7.5, 8, 0, 1])

print("\n一元函数")
print(np.sqrt(arr1))

print("\n二元函数")
print(np.add(arr1, arr2))



一元函数
[0.         1.         1.41421356 1.73205081 2.        ]

二元函数
[ 6.   8.5 10.   3.   5. ]


## 统计函数
这类函数会对数组中所有元素进行聚合，如求和、求平均

In [20]:
import numpy as np

arr = np.arange(5)

print(arr.mean())
print(arr.cumsum())

2.0
[ 0  1  3  6 10]


## 排序
- 对副本排序：np.sort(arr)
- 就地排序：arr.sort()

In [23]:
import numpy as np

arr = np.array([6, 7.5, 8, 0, 1])
print("对副本排序")
arr_copy = np.sort(arr)
print(arr)
print(arr_copy)

print("\n就地排序")
arr.sort()
print(arr)


对副本排序
[6.  7.5 8.  0.  1. ]
[0.  1.  6.  7.5 8. ]

就地排序
[0.  1.  6.  7.5 8. ]
